apiVersion : apps/v1
kind: Deployment
metadata:
  name: app-site-deployment
  labels: 
    app: app-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-site
  template:
    metadata:
      labels:
        app: app-site
    spec:
      containers:
        - name: app-site
          image: acrregistrytf.azurecr.io/site:latest
          ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-site-loadbalancer-service
  labels:
      app: app-site
spec:
  type: LoadBalancer
  selector:
    app: app-site
  ports:
    - port: 80
      targetPort: 80